- hosts: localhost
   tasks:
          -name: Enable Flathub repository
          become: yes
          command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          -name: Install Spotify
          become: yes
          command: flatpak install --assumeyes flathub com.spotify.Client
          -name: Enable Night Light
          dconf:
                  key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
                  value: true
          -name: Set Night Light Temperature
          dconf:
                  key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
                  value: uint32 5500
          -name: Install Builder
          become: yes
          package:
                  name: gnome-builder
                  state: present
          -name: Remove Rhythmbox
          become: yes
          package:
                  name: rhythmbox
                  state: absent
          -name: Install GNOME Music
          become: yes
          package:
                  name: gnome-music
                  state: present
          -name: Remove Shotwell
          become: yes
          package:
                  name: shotwell
                  state: absent
